language: rust
sudo: false

notifications:
  email: false

# https://github.com/bors-ng/bors-ng/issues/441#issuecomment-410467524
branches:
  only:
    # Enable building pull requests.
    - master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying

matrix:
  include:
    - name: "Bors (stable)"
      if: branch = staging OR branch = trying
      rust: stable
    - name: "Bors (beta)"
      if: branch = staging OR branch = trying
      rust: beta
    - name: "Bors (nightly)"
      if: branch = staging OR branch = trying
      rust: nightly
    - name: "PR Open"
      if: type = pull_request AND branch = master
      rust: stable

addons:
  apt:
    packages:
      - lzma-dev

# https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

env:
  - LZMA_API_STATIC=1

before_script:
  - rustup component add clippy-preview

script:
  - set -e
  - cargo build --verbose --no-default-features --all
  - cargo build --verbose --all
  - cargo clippy --verbose --all-targets --all-features
  - cargo test --verbose --all
