notifications:
  email: false

language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - ( test $TRAVIS_RUST_VERSION != "nightly" || cargo install clippy )

script:
  - set -e
  - cargo build --verbose
  - cargo test --verbose
  - ( test $TRAVIS_RUST_VERSION == "nightly" || cargo clippy )