language: rust
sudo: true

notifications:
  email: false

# https://github.com/bors-ng/bors-ng/issues/441#issuecomment-410467524
branches:
  only:
    # Enable building pull requests.
    - master
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying

matrix:
  include:
    - name: "Bors (stable)"
      if: branch = staging OR branch = trying OR type = cron
      rust: stable
    - name: "Bors (beta)"
      if: branch = staging OR branch = trying OR type = cron
      rust: beta
    - name: "Bors (nightly)"
      if: branch = staging OR branch = trying OR type = cron
      rust: nightly
    - name: "PR Open"
      if: type = pull_request AND branch = master
      rust: stable

# https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

env:
  global:
  - LZMA_API_STATIC=1

addons:
  apt:
    packages:
      - lzma-dev

before_script:
  # Allow this step to fail in case clippy is not available for whatever reason
  - ( rustup component add clippy-preview || true )

script:
  - set -e
  - cargo build --verbose --no-default-features --all
  - cargo build --verbose --all
  # skip this step if clippy is not available, e.g., bad nightly
  # `|| true` to make the command always succeed, because the `set -e` would fail otherwise
  - ( which cargo-clippy >/dev/null 2>&1 && cargo clippy --verbose --all ) || true
  - cargo test --verbose --all
