[package]
name = "misc_utils"
version = "1.1.1"
authors = ["Jonas Bushart <jonas@bushart.org>"]
description = "A small collection of convenient and utility functions developed for personal use."
repository = "https://github.com/jonasbb/rust_misc_utils"
readme = "README.md"
keywords = ["misc", "utils", "convenience"]
license = "Unlicense"

[lib]
name = "misc_utils"
path = "src/lib.rs"

[dependencies]
bzip2 = "0.3"
error-chain = "0.11.0-rc.2"
flate2 = "0.2"
log = "0.3"
xz2 = "0.1"

[dev-dependencies]
pretty_assertions = "0.2"
tempfile = "2.0"
