[package]
authors = ["Jonas Bushart"]
description = "A small collection of convenient and utility functions developed for personal use."
documentation = "https://docs.rs/misc_utils/"
edition = "2021"
keywords = ["misc", "utils", "convenience"]
license = "Unlicense"
name = "misc_utils"
readme = "README.md"
repository = "https://github.com/jonasbb/rust_misc_utils"
version = "4.3.0"

[lib]
name = "misc_utils"
path = "src/lib.rs"

[features]
async-fs = [
    "tokio",
    "tokio/fs",
    "tokio/rt",
]
default = [
    "file-gz",
    "file-xz",
    "jsonl",
]
file-bz2 = ["bzip2"]
file-gz = ["flate2"]
file-xz = ["xz2"]
# A nice multi-threaded JSONL iterator which puts file reading and JSON parsing into its own
# threads.
jsonl = ["serde", "serde_json"]

[dependencies]
bzip2 = {version = "0.6.0", optional = true}
flate2 = {version = "1.0", optional = true}
log = "0.4"
num-traits = "0.2.6"
serde = {version = "1.0", optional = true}
serde_json = {version = "1.0", optional = true}
thiserror = "2.0.3"
tokio.default-features = false
tokio.optional = true
tokio.version = "1.17"
xz2 = {version = "0.1", optional = true}

[dev-dependencies]
anyhow = "1.0.34"
expect-test = "1.2.2"
pretty_assertions = "1.0"
# Optional dev-dependencies are not a thing :(
serde.features = ["derive"]
serde.version = "1.0"
tempfile = "3.0"
version-sync = "0.9.2"

[package.metadata.docs.rs]
# https://github.com/onur/docs.rs/pull/131
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[lints.rust]
missing_docs = "warn"
rust_2018_idioms = {level = "warn", priority = -1}
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"
variant_size_differences = "warn"
unsafe_code = "forbid"
unexpected_cfgs = {level = "warn", check-cfg = [
    'cfg(tarpaulin)',
    'cfg(tarpaulin_include)',
]}

[lints.clippy]
# alloc_instead_of_core = "warn"
# Checks for usage of `cloned()` on an `Iterator` or `Option` where `copied()` could be used instead.
cloned_instead_of_copied = "warn"
# Checks for literal calls to `Default::default()`.
default_trait_access = "warn"
# Checks for the presence of `_`, `::` or camel-case words outside ticks in documentation.
# Disabled due to FP: https://github.com/rust-lang/rust-clippy/issues/12075
doc_markdown = "warn"
# Checks for closures which only invoke a method on the closure argument and can be replaced by referencing the method directly.
redundant_closure_for_method_calls = "warn"
semicolon_if_nothing_returned = "warn"
